import addToChart from "../support/AddtoChart/Addtochart";
import loginPage from "../support/Login.Page/Login";
import checkout from "../support/Checkout/Checkout";
import ReviewProduct from "../support/Checkout/Review";
const inputan = require("../fixtures/SignUp.json");
const { should } = require("chai");
const data = require("../fixtures/Data.json");

describe("Test website Magento", () => {
  const LoginPage = new loginPage();
  const AddtoChart = new addToChart();
  const Checkout = new checkout();
  const reviewProduct = new ReviewProduct();
  beforeEach(() => {
    cy.visit("");
  });
  it("Add_To_Cart_With_Login", () => {
    cy.get(LoginPage.signInBtn).click();
    cy.get(LoginPage.email).type(inputan.Valid_email);
    cy.get(LoginPage.password).type(inputan.Valid_password);
    cy.get(LoginPage.BtnSignIn).click();
    cy.get(AddtoChart.shoppePantsBtn).click();
    cy.get(AddtoChart.product).click();
    cy.get(AddtoChart.size).click();
    cy.get(AddtoChart.color).click();
    cy.get(AddtoChart.Quantity).clear().type("{upArrow}{upArrow}{upArrow}{upArrow}");
    cy.get(AddtoChart.BtnAddToCart).click();
    cy.wait(5000);
    cy.contains("You added").should("be.visible");
    cy.get(Checkout.CheckoutBtn).click({ force: true });
    cy.get(Checkout.ProcedBtn).click({ force: true });
    cy.wait(5000);
    // cy.get("Shipping Address").should("be.visible");
    cy.get(Checkout.email).type(inputan.New_Email, { force: true });
    cy.get(Checkout.firstnamee).type(inputan.FisrtName, { force: true });
    cy.get(Checkout.lastnamee).type(inputan.LastName, { force: true });
    cy.get(Checkout.company).type(data.company, { force: true });
    cy.get(Checkout.street1).type(data.streetAddress1, { force: true });
    cy.get(Checkout.street2).type(data.streetAddress2, { force: true });
    cy.get(Checkout.street3).type(data.streetAddress2, { force: true });
    cy.get(Checkout.city).type(data.City, { force: true });
    cy.get(Checkout.region).select("Alaska").should("have.value", "2");
    cy.get(Checkout.postcode).type(data.Postcode, { force: true });
    // cy.get(".message").go("forward");
    cy.get(Checkout.contry).select("Andorra").should("have.value", "AD");
    cy.get(Checkout.NoTelp).type(data.No_Hp, { force: true });
    cy.get(Checkout.Radio).check();
    cy.get(Checkout.Btn_Next).click();
    cy.wait(5000);
    cy.get(reviewProduct.CheckMatchShippingDetail).click();
    cy.get(reviewProduct.Discount).click();
    cy.get(reviewProduct.Btn_PlaceOrder).click();
    cy.wait(5000);
    cy.get(".base").should("be.visible");
  });
  it("Add_To_Cart_With_No_Login", () => {
    // cy.get(LoginPage.signInBtn).click();
    // cy.get(LoginPage.email).type(inputan.New_Email);
    // cy.get(LoginPage.password).type(inputan.New_Password);
    // cy.get(LoginPage.BtnSignIn).click();
    cy.get(AddtoChart.shoppePantsBtn).click();
    cy.get(AddtoChart.product).click();
    cy.get(AddtoChart.size).click();
    cy.get(AddtoChart.color).click();
    cy.get(AddtoChart.Quantity).clear().type("{upArrow}{upArrow}{upArrow}{upArrow}");
    cy.get(AddtoChart.BtnAddToCart).click();
    cy.wait(5000);
    cy.contains("You added").should("be.visible");
    cy.get(Checkout.CheckoutBtn).click({ force: true });
    cy.get(Checkout.ProcedBtn).click({ force: true });
    cy.wait(5000);
    // cy.get("Shipping Address").should("be.visible");
    cy.get(Checkout.email).type("dana@mail.com", { force: true });
    cy.get(Checkout.firstnamee).type(inputan.FisrtName, { force: true });
    cy.get(Checkout.lastnamee).type(inputan.LastName, { force: true });
    cy.get(Checkout.company).type(data.company, { force: true });
    cy.get(Checkout.street1).type(data.streetAddress1, { force: true });
    cy.get(Checkout.street2).type(data.streetAddress2, { force: true });
    cy.get(Checkout.street3).type(data.streetAddress2, { force: true });
    cy.get(Checkout.city).type(data.City, { force: true });
    cy.get(Checkout.region).select("Alaska").should("have.value", "2");
    cy.get(Checkout.postcode).type(data.Postcode, { force: true });
    // cy.get(".message").go("forward");
    cy.get(Checkout.contry).select("Andorra").should("have.value", "AD");
    cy.get(Checkout.NoTelp).type(data.No_Hp, { force: true });
    cy.get(Checkout.Radio).check();
    cy.get(Checkout.Btn_Next).click();
    cy.wait(5000);
    cy.get(reviewProduct.CheckMatchShippingDetail).click();
    cy.get(reviewProduct.Discount).click();
    cy.get(reviewProduct.Btn_PlaceOrder).click();
    cy.wait(5000);
    cy.get(".base").should("be.visible");
  });
});
